/**
 * Build information generated at build time
 * DO NOT EDIT - This file is automatically generated by scripts/build-info.sh
 */

export const BUILD_INFO = {
  version: '1.0.40',
  gitHash: '7dc0f9b',
  gitBranch: 'main',
  buildTime: '2026-02-04T06:32:28Z',
  nodeVersion: 'v25.2.1',
  isDirty: true,
} as const;

export type BuildInfo = typeof BUILD_INFO;
