/**
 * Build information generated at build time
 * DO NOT EDIT - This file is automatically generated by scripts/build-info.sh
 */

export const BUILD_INFO = {
  version: '1.0.4',
  gitHash: '37c6efe',
  gitBranch: 'preview',
  buildTime: '2026-01-25T02:26:46Z',
  nodeVersion: 'v25.2.1',
  isDirty: false,
} as const;

export type BuildInfo = typeof BUILD_INFO;
