/**
 * Build information generated at build time
 * DO NOT EDIT - This file is automatically generated by scripts/build-info.sh
 */

export const BUILD_INFO = {
  version: '1.0.19',
  gitHash: '44d62da',
  gitBranch: 'main',
  buildTime: '2026-02-01T20:42:27Z',
  nodeVersion: 'v25.2.1',
  isDirty: true,
} as const;

export type BuildInfo = typeof BUILD_INFO;
